### ISSUE TITLE
ZeroDivisionError exception raised when target reflector not resolvable in DNS

### ISSUE THREAD

**Issue by vanilladuck** [dropbox/llama-archive#16]
When a Collector configuration contains a target hostname which is not resolvable (for a Reflector) and the Collector is using `udp=True`, an exception occurs. While the exception is based around a simple math error, the root cause is lack of viable host which can be sent probes. 

```
INFO 2017-01-29 21:19:16,852 [collector]: Starting Llama Collector, version 0.0.1a7
INFO 2017-01-29 21:19:16,854 [config]: Loaded configuration with 1 targets
INFO 2017-01-29 21:19:16,854 [base]: Scheduler started
INFO 2017-01-29 21:19:16,855 [collector]: Creating metrics for HostThatDoesntExist: [Tag(key='tag1', value='value1'), Tag(key='tag2', value='value2')]
INFO 2017-01-29 21:19:16,865 [base]: Added job "Collection.collect" to job store "default"
INFO 2017-01-29 21:19:16,868 [_internal]:  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
INFO 2017-01-29 21:19:26,866 [base]: Running job "Collection.collect (trigger: interval[0:00:10], next run at: 2017-01-29 21:19:26 UTC)" (scheduled at 2017-01-29 21:19:26.864910+00:00)
INFO 2017-01-29 21:19:26,866 [collector]: Assigning target host: HostThatDoesntExist
ERROR 2017-01-29 21:19:26,899 [base]: Job "Collection.collect (trigger: interval[0:00:10], next run at: 2017-01-29 21:19:36 UTC)" raised an exception
Traceback (most recent call last):
  File "/home/breed/git/llama/venv/lib/python2.7/site-packages/APScheduler-3.3.0-py2.7.egg/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/breed/git/llama/llama/collector.py", line 59, in collect
    loss, rtt, host = job.result()
  File "/home/breed/git/llama/venv/lib/python2.7/site-packages/futures-3.0.5-py2.7.egg/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/home/breed/git/llama/venv/lib/python2.7/site-packages/futures-3.0.5-py2.7.egg/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/breed/git/llama/llama/ping.py", line 68, in send_udp
    return ProbeResults(sender.stats.loss, sender.stats.rtt_avg, target)
  File "/home/breed/git/llama/llama/udp.py", line 189, in stats
    loss = round(float(lost) / float(sent), 1) * 100
ZeroDivisionError: float division by zero
```

**Comment by vanilladuck** [comment]
This problem begs an interesting question:  Should the application (`llama_collector`) be performing DNS resolutions inside the application?

For a reachability tool, like LLAMA, the answer is probably 'no'. Isolating all meta data to the configuration files and reducing the number of calls to external systems in LLAMA components will provide a better separation of concerns.  Here is a proposal:

## Current Behavior
1) Operators can use either hostnames or IP addresses to define target reflectors in YAML config.
2) Upon startup, the collector assigns two tags to metrics: `dst_host` and `src_host`. If src_host isn't supplied, it is resolved locally.
3) It's up to the underlying `hping3` process or `socket.DGRAM_SOCK` library to determine how to reach the hostname or IP.

## Proposed Behavior
1) Require IP addresses only as reflector targets in YAML (future: this extends nicely to IPv6)
2) Automatically add two tags to every SRC-DST metric in the collector: `src_ip` and `dst_ip`
3) Leave it up to the discretion of the operator if hostnames need be identified in metric data as tags (results in timeseries data upstream)

This will result in handing probe libraries target addresses which are immediately usable and reduce the potential for DNS lookup issues inside the application. Perhaps a performance increase at large scale (for varying values of "large scale" ;)

**Comment by vanilladuck** [comment]
Also to note:
The divide-by-zero exception should be addressed on it's own ;-)
